CREATE TABLE TB_USUARIOS (
    PK_USUARIO INTEGER,
    FK_CIUDAD INTEGER,
    NOMBRE VARCHAR2(500),
    APELLIDO VARCHAR(500),
    EMAIL VARCHAR(500),
    CEDULA INTEGER
);

CREATE TABLE TB_CIUDAD (
    PK_CIUDAD INTEGER,
    PAIS VARCHAR(100),
    NOMBRE VARCHAR(100)
);

CREATE TABLE TB_USUARIOS_OFUSCADOS (
    PK_USUARIO INTEGER,
    FK_CIUDAD INTEGER,
    NOMBRE VARCHAR2(500),
    APELLIDO VARCHAR(500),
    EMAIL VARCHAR(500),
    CEDULA INTEGER,
    UUID RAW(16)
);

CREATE TABLE TB_CIUDAD_OFUSCADA (
    PK_CIUDAD INTEGER,
    PAIS VARCHAR(100),
    NOMBRE VARCHAR(100)
);

INSERT INTO TB_CIUDAD (PK_CIUDAD, PAIS, NOMBRE) VALUES (1, 'COLOMBIA', 'MEDELLÍN');
INSERT INTO TB_CIUDAD (PK_CIUDAD, PAIS, NOMBRE) VALUES (2, 'COLOMBIA', 'BOGOTÁ');
INSERT INTO TB_CIUDAD (PK_CIUDAD, PAIS, NOMBRE) VALUES (3, 'COLOMBIA', 'CALI');

INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (1, 1, 'Juan', 'Pérez', 'juan.perez@email.com', 123456789);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (2, 1, 'Laura', 'González', 'laura.gonzalez@email.com', 987654321);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (3, 2, 'Carlos', 'Martínez', 'carlos.martinez@email.com', 123987654);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (4, 2, 'Sofía', 'López', 'sofia.lopez@email.com', 567890123);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (5, 3, 'Alejandro', 'Ramírez', 'alejandro.ramirez@email.com', 765432189);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (6, 3, 'María', 'Fernandez', 'maria.fernandez@email.com', 234567890);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (7, 1, 'Roberto', 'Garcia', 'roberto.garcia@email.com', 345678901);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (8, 1, 'Carmen', 'Ruiz', 'carmen.ruiz@email.com', 456789012);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (9, 2, 'Antonio', 'Morales', 'antonio.morales@email.com', 567890123);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (10, 2, 'Patricia', 'Jimenez', 'patricia.jimenez@email.com', 678901234);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (11, 3, 'Jorge', 'Moreno', 'jorge.moreno@email.com', 789012345);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (12, 1, 'Lucía', 'Mendez', 'lucia.mendez@email.com', 890123456);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (13, 1, 'Felipe', 'Gutierrez', 'felipe.gutierrez@email.com', 901234567);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (14, 2, 'Daniela', 'Castillo', 'daniela.castillo@email.com', 123456788);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (15, 2, 'Manuel', 'López', 'manuel.lopez@email.com', 234567899);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (16, 3, 'Andrea', 'Sánchez', 'andrea.sanchez@email.com', 345678910);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (17, 1, 'Oscar', 'Martínez', 'oscar.martinez@email.com', 456789021);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (18, 1, 'Silvia', 'Pérez', 'silvia.perez@email.com', 567890132);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (19, 2, 'Miguel', 'Diaz', 'miguel.diaz@email.com', 678901243);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (20, 2, 'Sara', 'Morales', 'sara.morales@email.com', 789012354);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (21, 3, 'Carlos', 'Gómez', 'carlos.gomez@email.com', 890123465);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (22, 1, 'Ana', 'Ortiz', 'ana.ortiz@email.com', 901234576);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (23, 1, 'Francisco', 'Ruiz', 'francisco.ruiz@email.com', 123456787);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (24, 2, 'Verónica', 'García', 'veronica.garcia@email.com', 234567898);
INSERT INTO TB_USUARIOS (PK_USUARIO, FK_CIUDAD, NOMBRE, APELLIDO, EMAIL, CEDULA) VALUES (25, 3, 'Esteban', 'Quito', 'esteban.quito@email.com', 345678909);
